### ISSUE TITLE
Volume Icon not supported in Elementary OS (brightness one bad supported)

### ISSUE THREAD

**Issue by robby14** [TheTonicTeam/TonicOS-Ultraflat#2]
In Elementary os as you can see at the volume is not associated an icon:
![screenshot from 2015-04-29 11 23 15](https://cloud.githubusercontent.com/assets/11992666/7388035/67a3a752-ee62-11e4-88d9-c31e7f285cf9.png)
also the brightness icon it's not good because it's white on a light grey background so you cannot see properly:
![screenshot from 2015-04-29 11 23 38](https://cloud.githubusercontent.com/assets/11992666/7388058/92914e56-ee62-11e4-8f2b-f2fee08abcc0.png)

**Comment by ghost** [comment]
As I said in your other issue, try to fill a icon name after "Inherits" key may help
