### ISSUE TITLE
In elementary os bad lots of icons are not supported (also inside applications)

### ISSUE THREAD

**Issue by robby14** [TheTonicTeam/TonicOS-Ultraflat#3]
As you can see below, "Photo" application (that is the default elementary os application to view and edit pothos) has not an applications as well as several other applications, I guess that it's impossible to give to all the applications out there an icon but you could do that when an application is not available the icon could be taken from another icon set (as for example the elmentary os standard one, or another one):
![screenshot from 2015-04-29 11 29 09](https://cloud.githubusercontent.com/assets/11992666/7388163/70c3f462-ee63-11e4-9a8e-b4214f198ab2.png)

Furthemore inside "Photos" as well as in lots of menus or in other applications there are lots of not supported icons (as you can see from the below photo at the bottom-left just above the dock), could you do also in this case that when an icon is not supported it'll be taken from another icon set like the standard one of elementary os?
![screenshot from 2015-04-29 11 28 55](https://cloud.githubusercontent.com/assets/11992666/7388221/dbb5cbb0-ee63-11e4-9097-3d722571deae.png)

**Comment by ghost** [comment]
Thanks for report, originally this theme is not for elementary-os , it's mostly for xfce 4.X, I've tested it also under cinnamon and gnome. For this issue, you can go to the icon folder, open index.theme, fill "elementary-icon-name" as value of "Inherits" key.
![image](https://cloud.githubusercontent.com/assets/9502051/7388845/368a5b78-ee9b-11e4-84da-c98bde1ac516.png)

**Comment by robby14** [comment]
Thank you

**Comment by ghost** [comment]
You're welcome :)

**Comment by robby14** [comment]
Is also possible to keep to the stock icons in the system and inside the applications?
I'd like, if possible to have your icons only for the app themselves and not for the icons inside the apps, I don't know if I explained myself in a good way...

Thank you
