### ISSUE TITLE
Is this theme still alive?

### ISSUE THREAD

**Issue by robby14** [TheTonicTeam/TonicOS-Ultraflat#4]
Hi,
I guess this one is one of the best icons theme, but I see it's no longer maintained. 
Is the development of it finished?

roberto

**Comment by ghost** [comment]
Hi Roberto,
Unfortunately, The original theme has been ensured be discontinued, I suppose this repository is the only source of this theme. Yep, this is pretty a good icon theme, I think we won't give up, but recently our development not focus on here, and planning to move to gitlab as main host service. It must be a good new if you would like to help us maintenance and keeping this theme alive.
Ethan

**Comment by robby14** [comment]
I hope your focus could come back here a day :) anyway I don't have experience in making icons, but I'd like to help to do them... Anyway I'm getting graduated this year ( semptember) so I'm very busy, after that I guess I could do something

**Comment by ghost** [comment]
Thank you! If you have any questions just post here or send me email. Good luck with your study :)

**Comment by robby14** [comment]
;)
